// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:village_project/firebase_config_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseConfigKeys.firebaseWebApiKey!,
    appId: '1:889017444695:web:e0c0a4301191acca3bf612',
    messagingSenderId: '889017444695',
    projectId: 'fastdata-7c185',
    authDomain: 'fastdata-7c185.firebaseapp.com',
    databaseURL: 'https://fastdata-7c185-default-rtdb.firebaseio.com',
    storageBucket: 'fastdata-7c185.firebasestorage.app',
    measurementId: 'G-L2K9SKW3NH',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseConfigKeys.firebaseAndroidApiKey,
    appId: '1:889017444695:android:fe5c783ec51e7beb3bf612',
    messagingSenderId: '889017444695',
    projectId: 'fastdata-7c185',
    databaseURL: 'https://fastdata-7c185-default-rtdb.firebaseio.com',
    storageBucket: 'fastdata-7c185.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseConfigKeys.fireabaseIosAndroidKey,
    appId: '1:889017444695:ios:007800b7bcc63ab13bf612',
    messagingSenderId: '889017444695',
    projectId: 'fastdata-7c185',
    databaseURL: 'https://fastdata-7c185-default-rtdb.firebaseio.com',
    storageBucket: 'fastdata-7c185.firebasestorage.app',
    iosBundleId: 'com.example.villageProject',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: FirebaseConfigKeys.firebaseMacosApiKey!,
    appId: '1:889017444695:ios:007800b7bcc63ab13bf612',
    messagingSenderId: '889017444695',
    projectId: 'fastdata-7c185',
    databaseURL: 'https://fastdata-7c185-default-rtdb.firebaseio.com',
    storageBucket: 'fastdata-7c185.firebasestorage.app',
    iosBundleId: 'com.example.villageProject',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: FirebaseConfigKeys.firebaseWindowsApiKey!,
    appId: '1:889017444695:web:e902677c5ef4596d3bf612',
    messagingSenderId: '889017444695',
    projectId: 'fastdata-7c185',
    authDomain: 'fastdata-7c185.firebaseapp.com',
    databaseURL: 'https://fastdata-7c185-default-rtdb.firebaseio.com',
    storageBucket: 'fastdata-7c185.firebasestorage.app',
    measurementId: 'G-PMT777X0FN',
  );
}
